before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: BuDYG37HzeyxH4EhXEbyxJITuLQGcujGpUnN0ONJRccg0ufNfl8cOl0Ab6Jw+4w6vCU4bfkMO8uW3PXX5bIl/fvOUeSL0yVMBSKgWDfZIaHDjOr/tCETXx0V6PkucWjV4LqCDEfPjor+iPNsIv0y5AuC0+G3wc8GzQ1Y68YJ4WoI/FcasUh+GnCBTvx0QPLBzry5jFpoF1YF12L+QDm/JKaBcW8WQGbWDX1rEqv1pJYh/qjx2yXLXn3PoOhYM06bzDOBQBjqy+wk0QvUpk0Bc+ooxOwmrMreygS3Rd3RX0r6zWFxhqM2eEIs5f+hHQTpgw9i7LusNEpEhpQeej1PvLn2e5PWC+drcVPaNZEI1kHV8W8/lqE9TK8Wotx44tKVkc9r+i2pSonw5Ou21vIv3epbQXV2Q7XhpGGL23jxw4Gfxia3ZBUttD3uFQuVnGsup4d7wuZS2XNKbSlti46+tagUi4vCckYIXRsoNLS4dnjxHH5qWOkXRKYVoKor53g/FWqekv+J93ilkxRkg6gdvMOIDqDFrn1R8qBtGtZT6U8pc+rVYV7A0rivKWuTTAvNCpyoMU6DQfwVTAFznDaXy5/PiKoH2AsO0G+xID57+hch0gaQ19Zc6FvxpuLiFO+jexGBITzSTE0bUJ76txRtcBNtypMfGutjrx0gFme08vk= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
